/**
 * Generated by scripts/generate-pillar-index.mjs. Do not edit by hand.
 *
 * One hub pillar guide per file. 6 pillars.
 */
import type { GuidePageData } from '../../guideContent';
import { boiseHomeMaintenanceGuide } from './boise-home-maintenance-guide';
import { boiseHomeRepairCostGuide } from './boise-home-repair-cost-guide';
import { firstTimeHomeownerRepairHandbook } from './first-time-homeowner-repair-handbook';
import { hireAHandymanTreasureValley } from './hire-a-handyman-treasure-valley';
import { smallHomeUpgradesThatPayOff } from './small-home-upgrades-that-pay-off';
import { treasureValleyExteriorHomeCareGuide } from './treasure-valley-exterior-home-care-guide';

export const PILLAR_GUIDES: GuidePageData[] = [
  boiseHomeMaintenanceGuide,
  boiseHomeRepairCostGuide,
  firstTimeHomeownerRepairHandbook,
  hireAHandymanTreasureValley,
  smallHomeUpgradesThatPayOff,
  treasureValleyExteriorHomeCareGuide,
];
