/**
 * Generated by scripts/generate-wave2-index.mjs. Do not edit by hand.
 *
 * Every hand-authored article lives in its own file in this directory and is
 * collected here. 34 posts.
 */
import type { BlogPostData } from '../../blogContent';
import { adaVsCanyonCountyPermitTimelines } from './ada-vs-canyon-county-permit-timelines';
import { agingInPlaceHomeDesign } from './aging-in-place-home-design';
import { boiseBuildingPermitGuide } from './boise-building-permit-guide';
import { caulkingGuideBoiseHomes } from './caulking-guide-boise-homes';
import { commonToiletProblemsAndFixes } from './common-toilet-problems-and-fixes';
import { deckMaintenanceBoise } from './deck-maintenance-boise';
import { diyVsHiringAHandyman } from './diy-vs-hiring-a-handyman';
import { drywallRepairCostBoise } from './drywall-repair-cost-boise';
import { energySavingHomeFixesBoise } from './energy-saving-home-fixes-boise';
import { fenceRepairTreasureValley } from './fence-repair-treasure-valley';
import { fixingSqueakyFloorsAndStickingDoors } from './fixing-squeaky-floors-and-sticking-doors';
import { gutterCleaningScheduleBoise } from './gutter-cleaning-schedule-boise';
import { handymanPricesBoise } from './handyman-prices-boise';
import { handymanRedFlags } from './handyman-red-flags';
import { handymanVsContractor } from './handyman-vs-contractor';
import { homeMaintenanceBudgetIdaho } from './home-maintenance-budget-idaho';
import { homeRepairsBeforeSellingBoise } from './home-repairs-before-selling-boise';
import { hourlyRateVsFlatRateHandyman } from './hourly-rate-vs-flat-rate-handyman';
import { howLongDoCommonHomeRepairsTake } from './how-long-do-common-home-repairs-take';
import { howToBudgetHomeRepairsBoise } from './how-to-budget-home-repairs-boise';
import { howToCompareHandymanQuotes } from './how-to-compare-handyman-quotes';
import { howToPatchDrywall } from './how-to-patch-drywall';
import { interiorPaintTouchUpGuide } from './interior-paint-touch-up-guide';
import { newHomePunchListHandyman } from './new-home-punch-list-handyman';
import { preparingYourBoiseHomeForWinter } from './preparing-your-boise-home-for-winter';
import { questionsToAskAHandyman } from './questions-to-ask-a-handyman';
import { replacingFaucetsAndFixtures } from './replacing-faucets-and-fixtures';
import { seasonalHomeMaintenanceChecklistBoise } from './seasonal-home-maintenance-checklist-boise';
import { smallHomeUpgradeIdeasBoise } from './small-home-upgrade-ideas-boise';
import { tvMountingAndAnchoringGuide } from './tv-mounting-and-anchoring-guide';
import { whatSmallHomeRepairsCostBoise } from './what-small-home-repairs-cost-boise';
import { whatToExpectFirstHandymanVisit } from './what-to-expect-first-handyman-visit';
import { whoSuppliesMaterialsHandymanJobs } from './who-supplies-materials-handyman-jobs';
import { whyHandymanQuotesVary } from './why-handyman-quotes-vary';

export const WAVE2_POSTS: BlogPostData[] = [
  adaVsCanyonCountyPermitTimelines,
  agingInPlaceHomeDesign,
  boiseBuildingPermitGuide,
  caulkingGuideBoiseHomes,
  commonToiletProblemsAndFixes,
  deckMaintenanceBoise,
  diyVsHiringAHandyman,
  drywallRepairCostBoise,
  energySavingHomeFixesBoise,
  fenceRepairTreasureValley,
  fixingSqueakyFloorsAndStickingDoors,
  gutterCleaningScheduleBoise,
  handymanPricesBoise,
  handymanRedFlags,
  handymanVsContractor,
  homeMaintenanceBudgetIdaho,
  homeRepairsBeforeSellingBoise,
  hourlyRateVsFlatRateHandyman,
  howLongDoCommonHomeRepairsTake,
  howToBudgetHomeRepairsBoise,
  howToCompareHandymanQuotes,
  howToPatchDrywall,
  interiorPaintTouchUpGuide,
  newHomePunchListHandyman,
  preparingYourBoiseHomeForWinter,
  questionsToAskAHandyman,
  replacingFaucetsAndFixtures,
  seasonalHomeMaintenanceChecklistBoise,
  smallHomeUpgradeIdeasBoise,
  tvMountingAndAnchoringGuide,
  whatSmallHomeRepairsCostBoise,
  whatToExpectFirstHandymanVisit,
  whoSuppliesMaterialsHandymanJobs,
  whyHandymanQuotesVary,
];
