/**
 * Per-slug hero imagery for blog posts and guides.
 *
 * Generated by scripts/generate-blog-image-registry.ts from the content layer.
 * Do not hand-edit. Change the assignment table in that script and re-run
 * `npm run images:blog`.
 */

export type BlogImageSource = 'handyman';

export interface BlogImageEntry {
  hero: string;
  thumbnail?: string;
  alt: string;
  topicTags: string[];
  source: BlogImageSource;
}

export const BLOG_IMAGE_REGISTRY: Record<string, BlogImageEntry> = {
  'ada-vs-canyon-county-permit-timelines': {
    hero: '/images/handyman/permit-paperwork.webp',
    alt: 'Permit paperwork and folded residential drawings on a municipal counter with a hand holding a pen',
    topicTags: ["permits","ada county","canyon county","home repairs","costs"],
    source: 'handyman',
  },
  'aging-in-place-home-design': {
    hero: '/images/handyman/grab-bar-install.webp',
    alt: 'Brushed nickel safety grab bar freshly installed on white subway tile in a walk-in shower',
    topicTags: ["aging in place","grab bars","home safety","installs"],
    source: 'handyman',
  },
  'boise-building-permit-guide': {
    hero: '/images/handyman/permit-paperwork.webp',
    alt: 'Permit paperwork and folded residential drawings on a municipal counter with a hand holding a pen',
    topicTags: ["permits","boise","home repairs","hiring","costs"],
    source: 'handyman',
  },
  'caulking-guide-boise-homes': {
    hero: '/images/handyman/service-caulking.webp',
    alt: 'Caulk gun applying a clean white silicone bead where a bathtub meets white subway tile',
    topicTags: ["caulking","home maintenance","sealing","boise","home"],
    source: 'handyman',
  },
  'common-toilet-problems-and-fixes': {
    hero: '/images/handyman/toilet-repair.webp',
    alt: 'Plumber lifting the porcelain lid off a toilet tank to service the fill valve in a clean bathroom',
    topicTags: ["plumbing","toilet repair","boise","repairs"],
    source: 'handyman',
  },
  'deck-maintenance-boise': {
    hero: '/images/handyman/deck-board-replacement.webp',
    alt: 'Gloved hands replacing a weathered deck board with a new cedar board on a backyard deck',
    topicTags: ["deck","exterior","maintenance","boise"],
    source: 'handyman',
  },
  'diy-vs-hiring-a-handyman': {
    hero: '/images/handyman/toolbag-ready.webp',
    alt: 'Neatly organized canvas tool bag with drill, levels, and tape measure staged on a drop cloth in a living room',
    topicTags: ["diy","hiring","home repairs","handyman","costs"],
    source: 'handyman',
  },
  'drywall-repair-cost-boise': {
    hero: '/images/handyman/service-drywall-repair.webp',
    alt: 'Hands spreading joint compound over a drywall patch with a taping knife in a bright room',
    topicTags: ["drywall","cost","boise","repairs","costs"],
    source: 'handyman',
  },
  'energy-saving-home-fixes-boise': {
    hero: '/images/handyman/weatherstripping.webp',
    alt: 'Hands applying self-adhesive foam weatherstripping to a white exterior door frame to seal drafts',
    topicTags: ["energy efficiency","weatherstripping","caulking","boise","home maintenance"],
    source: 'handyman',
  },
  'fence-repair-treasure-valley': {
    hero: '/images/handyman/service-fence-repair.webp',
    alt: 'Gloved hands screwing a new cedar picket onto a backyard fence rail with a cordless drill',
    topicTags: ["fence repair","exterior","treasure valley","boise"],
    source: 'handyman',
  },
  'fixing-squeaky-floors-and-sticking-doors': {
    hero: '/images/handyman/door-hinge-fix.webp',
    alt: 'Hand tightening the hinge screws of a white interior door with a screwdriver',
    topicTags: ["floors","doors","repairs","carpentry"],
    source: 'handyman',
  },
  'gutter-cleaning-schedule-boise': {
    hero: '/images/handyman/hero-gutter-cleaning.webp',
    alt: 'Worker on a ladder clearing autumn leaves from the rain gutter of a single-story suburban Boise home',
    topicTags: ["gutter cleaning","home maintenance","boise","exterior","home"],
    source: 'handyman',
  },
  'handyman-prices-boise': {
    hero: '/images/handyman/estimate-clipboard.webp',
    alt: 'Clipboard with estimate paper, calculator, pencil, and tape measure arranged on a wood kitchen table',
    topicTags: ["cost","handyman rates","boise","hiring","costs"],
    source: 'handyman',
  },
  'handyman-red-flags': {
    hero: '/images/handyman/consult-doorstep-branded-v2.webp',
    alt: 'Handyman reviewing a small-job checklist on a clipboard with a homeowner at their front door',
    topicTags: ["hiring a handyman","boise","quotes","home repairs","costs"],
    source: 'handyman',
  },
  'handyman-vs-contractor': {
    hero: '/images/handyman/toolbag-ready.webp',
    alt: 'Neatly organized canvas tool bag with drill, levels, and tape measure staged on a drop cloth in a living room',
    topicTags: ["hiring a handyman","contractors","boise","home repairs","costs"],
    source: 'handyman',
  },
  'home-maintenance-budget-idaho': {
    hero: '/images/handyman/estimate-clipboard.webp',
    alt: 'Clipboard with estimate paper, calculator, pencil, and tape measure arranged on a wood kitchen table',
    topicTags: ["budgeting","home maintenance","idaho","costs"],
    source: 'handyman',
  },
  'home-repairs-before-selling-boise': {
    hero: '/images/handyman/front-door-repaint.webp',
    alt: 'Freshly repainted sage green craftsman front door with painter\'s tape being peeled away',
    topicTags: ["home repairs","selling a house","boise","punch list","repairs"],
    source: 'handyman',
  },
  'hourly-rate-vs-flat-rate-handyman': {
    hero: '/images/handyman/estimate-clipboard.webp',
    alt: 'Clipboard with estimate paper, calculator, pencil, and tape measure arranged on a wood kitchen table',
    topicTags: ["handyman rates","pricing","boise","hiring a handyman","costs"],
    source: 'handyman',
  },
  'how-long-do-common-home-repairs-take': {
    hero: '/images/handyman/hero-door-repair-branded-v2.webp',
    alt: 'Handyman adjusting a sticking white interior door in a bright Idaho home with a tool bag on a drop cloth nearby',
    topicTags: ["home repairs","boise","drywall repair","plumbing repairs","repairs"],
    source: 'handyman',
  },
  'how-to-budget-home-repairs-boise': {
    hero: '/images/handyman/repair-materials.webp',
    alt: 'Assorted screws, wall anchors, and picture hangers organized in a small parts tray on a workbench',
    topicTags: ["home repair costs","budgeting","boise","punch list","costs"],
    source: 'handyman',
  },
  'how-to-compare-handyman-quotes': {
    hero: '/images/handyman/estimate-clipboard.webp',
    alt: 'Clipboard with estimate paper, calculator, pencil, and tape measure arranged on a wood kitchen table',
    topicTags: ["handyman quotes","hiring a handyman","boise","pricing","costs"],
    source: 'handyman',
  },
  'how-to-patch-drywall': {
    hero: '/images/handyman/service-drywall-repair.webp',
    alt: 'Hands spreading joint compound over a drywall patch with a taping knife in a bright room',
    topicTags: ["drywall repair","repairs","boise","diy"],
    source: 'handyman',
  },
  'interior-paint-touch-up-guide': {
    hero: '/images/handyman/service-painting.webp',
    alt: 'Painter cutting in crisp paint along white window trim with an angled brush and painter\'s tape',
    topicTags: ["painting","paint touch-up","repairs","boise"],
    source: 'handyman',
  },
  'new-home-punch-list-handyman': {
    hero: '/images/handyman/punch-list-markers.webp',
    alt: 'Blue painter\'s tape markers on a wall and window trim marking touch-up spots, notepad on the windowsill',
    topicTags: ["punch list","home maintenance","boise","new home","home"],
    source: 'handyman',
  },
  'preparing-your-boise-home-for-winter': {
    hero: '/images/handyman/winterize-spigot.webp',
    alt: 'Insulated faucet cover being fitted over an outdoor hose spigot with frost on the grass',
    topicTags: ["winterizing","home maintenance","boise","seasonal","home"],
    source: 'handyman',
  },
  'questions-to-ask-a-handyman': {
    hero: '/images/handyman/consult-doorstep-branded-v2.webp',
    alt: 'Handyman reviewing a small-job checklist on a clipboard with a homeowner at their front door',
    topicTags: ["hiring a handyman","boise","handyman costs","home repair","costs"],
    source: 'handyman',
  },
  'replacing-faucets-and-fixtures': {
    hero: '/images/handyman/service-plumbing.webp',
    alt: 'Hands installing a new brushed-nickel kitchen faucet with supply lines and a wrench at a farmhouse sink',
    topicTags: ["plumbing","faucet replacement","installs","boise"],
    source: 'handyman',
  },
  'seasonal-home-maintenance-checklist-boise': {
    hero: '/images/handyman/toolbag-ready.webp',
    alt: 'Neatly organized canvas tool bag with drill, levels, and tape measure staged on a drop cloth in a living room',
    topicTags: ["home maintenance","seasonal checklist","boise","gutters","winterizing"],
    source: 'handyman',
  },
  'small-home-upgrade-ideas-boise': {
    hero: '/images/handyman/cabinet-hardware-upgrade.webp',
    alt: 'Hands swapping new brushed brass knobs onto white shaker kitchen cabinet doors with a screwdriver',
    topicTags: ["home upgrades","installs","boise","painting","lighting"],
    source: 'handyman',
  },
  'tv-mounting-and-anchoring-guide': {
    hero: '/images/handyman/service-mounting.webp',
    alt: 'Handyman holding a bubble level and drill while installing a TV wall-mount bracket in a living room',
    topicTags: ["tv mounting","installs","boise","anchoring"],
    source: 'handyman',
  },
  'what-small-home-repairs-cost-boise': {
    hero: '/images/handyman/repair-materials.webp',
    alt: 'Assorted screws, wall anchors, and picture hangers organized in a small parts tray on a workbench',
    topicTags: ["handyman costs","boise","hiring a handyman","home repair","costs"],
    source: 'handyman',
  },
  'what-to-expect-first-handyman-visit': {
    hero: '/images/handyman/consult-doorstep-branded-v2.webp',
    alt: 'Handyman reviewing a small-job checklist on a clipboard with a homeowner at their front door',
    topicTags: ["hiring a handyman","boise","home repairs","quotes","costs"],
    source: 'handyman',
  },
  'who-supplies-materials-handyman-jobs': {
    hero: '/images/handyman/repair-materials.webp',
    alt: 'Assorted screws, wall anchors, and picture hangers organized in a small parts tray on a workbench',
    topicTags: ["materials","hiring","pricing","handyman","costs"],
    source: 'handyman',
  },
  'why-handyman-quotes-vary': {
    hero: '/images/handyman/estimate-clipboard.webp',
    alt: 'Clipboard with estimate paper, calculator, pencil, and tape measure arranged on a wood kitchen table',
    topicTags: ["handyman costs","hiring a handyman","boise","quotes","costs"],
    source: 'handyman',
  },
  'boise-home-maintenance-guide': {
    hero: '/images/handyman/toolbag-ready.webp',
    alt: 'Neatly organized canvas tool bag with drill, levels, and tape measure staged on a drop cloth in a living room',
    topicTags: ["maintenance","seasonal","checklist","home care","boise"],
    source: 'handyman',
  },
  'boise-home-repair-cost-guide': {
    hero: '/images/handyman/estimate-clipboard.webp',
    alt: 'Clipboard with estimate paper, calculator, pencil, and tape measure arranged on a wood kitchen table',
    topicTags: ["cost","handyman rates","home repair","pricing","boise"],
    source: 'handyman',
  },
  'first-time-homeowner-repair-handbook': {
    hero: '/images/handyman/hero-door-repair-branded-v2.webp',
    alt: 'Handyman adjusting a sticking white interior door in a bright Idaho home with a tool bag on a drop cloth nearby',
    topicTags: ["first-time homeowner","repairs","diy","basics","boise"],
    source: 'handyman',
  },
  'hire-a-handyman-treasure-valley': {
    hero: '/images/handyman/consult-doorstep-branded-v2.webp',
    alt: 'Handyman reviewing a small-job checklist on a clipboard with a homeowner at their front door',
    topicTags: ["hiring","handyman","vetting","quotes","boise"],
    source: 'handyman',
  },
  'small-home-upgrades-that-pay-off': {
    hero: '/images/handyman/cabinet-hardware-upgrade.webp',
    alt: 'Hands swapping new brushed brass knobs onto white shaker kitchen cabinet doors with a screwdriver',
    topicTags: ["upgrades","installs","painting","lighting","boise"],
    source: 'handyman',
  },
  'treasure-valley-exterior-home-care-guide': {
    hero: '/images/handyman/hero-gutter-cleaning.webp',
    alt: 'Worker on a ladder clearing autumn leaves from the rain gutter of a single-story suburban Boise home',
    topicTags: ["exterior","fence","deck","gutters","siding"],
    source: 'handyman',
  },
  'boise-handyman-guide': {
    hero: '/images/areas/boise.webp',
    alt: 'Established Boise, Idaho neighborhood of craftsman homes with covered porches and the Boise foothills rising behind the street',
    topicTags: ["boise","idaho","handyman","costs"],
    source: 'handyman',
  },
  'meridian-handyman-guide': {
    hero: '/images/areas/meridian.webp',
    alt: 'Craftsman two-story home lit at dusk on a landscaped subdivision lot in Meridian, Idaho',
    topicTags: ["meridian","idaho","handyman","costs"],
    source: 'handyman',
  },
  'eagle-handyman-guide': {
    hero: '/images/areas/eagle.webp',
    alt: 'Custom home on a landscaped Eagle, Idaho acreage lot at sunset with the foothills in the distance',
    topicTags: ["eagle","idaho","handyman","costs"],
    source: 'handyman',
  },
  'kuna-handyman-guide': {
    hero: '/images/areas/kuna.webp',
    alt: 'Modern farmhouse home on rural Kuna, Idaho acreage bordered by sagebrush and open farmland',
    topicTags: ["kuna","idaho","handyman","costs"],
    source: 'handyman',
  },
  'star-handyman-guide': {
    hero: '/images/areas/star.webp',
    alt: 'Riverfront home in Star, Idaho with a lawn running down to the Boise River and shade trees along the bank',
    topicTags: ["star","idaho","handyman","costs"],
    source: 'handyman',
  },
  'middleton-handyman-guide': {
    hero: '/images/areas/middleton.webp',
    alt: 'White farmhouse with a wraparound porch on a Middleton, Idaho parcel surrounded by wheat fields at sunset',
    topicTags: ["middleton","idaho","handyman","costs"],
    source: 'handyman',
  },
  'nampa-handyman-guide': {
    hero: '/images/areas/nampa.webp',
    alt: 'Established brick ranch home on a landscaped corner lot in Nampa, Idaho with farmland behind',
    topicTags: ["nampa","idaho","handyman","costs"],
    source: 'handyman',
  },
  'caldwell-handyman-guide': {
    hero: '/images/areas/caldwell.webp',
    alt: 'Stucco home overlooking the vineyards of the Sunnyslope wine district near Caldwell, Idaho at sunset',
    topicTags: ["caldwell","idaho","handyman","costs"],
    source: 'handyman',
  },
  'eagle-foothills-handyman-guide': {
    hero: '/images/areas/eagle.webp',
    alt: 'Custom home on a landscaped Eagle, Idaho acreage lot at sunset with the foothills in the distance',
    topicTags: ["eagle","the eagle foothills","idaho","handyman","costs"],
    source: 'handyman',
  },
  'hidden-springs-handyman-guide': {
    hero: '/images/areas/boise.webp',
    alt: 'Established Boise, Idaho neighborhood of craftsman homes with covered porches and the Boise foothills rising behind the street',
    topicTags: ["eagle","hidden springs","idaho","handyman","costs"],
    source: 'handyman',
  },
  'harris-ranch-handyman-guide': {
    hero: '/images/areas/boise.webp',
    alt: 'Established Boise, Idaho neighborhood of craftsman homes with covered porches and the Boise foothills rising behind the street',
    topicTags: ["boise","harris ranch","idaho","handyman","costs"],
    source: 'handyman',
  },
};

export const HUB_HERO_IMAGES: Record<string, string> = {
  'repairs-and-fixes': '/images/handyman/toolbag-ready.webp',
  'installs-and-upgrades': '/images/handyman/service-mounting.webp',
  'home-maintenance': '/images/handyman/service-caulking.webp',
  'costs-and-hiring': '/images/handyman/estimate-clipboard.webp',
  'exterior-and-outdoor': '/images/handyman/hero-gutter-cleaning.webp',
};

/** Retained for the setup script's interface; nothing is copied any more. */
export const BLOG_ASSET_COPY_MAP: Record<string, string> = {};
